// src/store/booksSlice.js

// Imports //

//Import createSlice from redux-toolkit
import { createSlice } from "@reduxjs/toolkit";
//Import the booksData data component
import { booksData } from "../data/BooksData.js";
//Import load and save sessionStorage utilities
import {
  loadFromSessionStorage,
  saveToSessionStorage,
} from "../utils/sessionStorageUtils.js";

//Load rawBooks from saved booksData with fallback to default booksData
const rawBooks = loadFromSessionStorage("booksData", booksData);

//convert books into plain objects
const initialState = rawBooks.map((book) => ({ ...book }));

// Create slice //

//Create a booksSlice
const booksSlice = createSlice({
  name: "books",
  initialState,
  //Declare reducers
  reducers: {
    //Color selection reducer action
    updateColor: (state, action) => {
      const { bookId, colorIndex } = action.payload;
      //Find the corresponding book by id
      const book = state.find((b) => b.id === bookId);
      if (book) {
        //then change the book.colorIndex to the corresponding inputted colorIndex
        book.colorIndex = colorIndex;
        //Save to sessionStorage
        saveToSessionStorage("booksData", state);
      }
    },
  },
});

//Export actions generated by createSlice
export const { updateColor } = booksSlice.actions;
//Export the reducer function
export default booksSlice.reducer;
