//booksSlice.js

// Imports //

//Import createSlice from redux-toolkit
import { createSlice } from "@reduxjs/toolkit";
//Import the booksData data component
import { booksData } from "../data/BooksData.js";
//Import load and save localStorage utilities
import {
  loadFromLocalStorage,
  saveToLocalStorage,
} from "../utils/localStorageUtils.js";

//Load rawBooks from saved booksData with fallback to default booksData
const rawBooks = loadFromLocalStorage("booksData", booksData);

//Convert any loaded books (including those created with constructors) into plain objects
//This is a fix suggested by ChatGPT to overcome an initial render issue...
// ...(couldn't change product color on first render) caused by the constructor
//...the saved constructor interfered with prototype links
//I was unwilling to abandon my constructor function and
//chose this fix above defining booksData with object literals
const initialState = rawBooks.map((book) => ({ ...book }));

// Create slice //

//Create a booksSlice
const booksSlice = createSlice({
  name: "books",
  initialState,
  //Declare reducers
  reducers: {
    //Color selection reducer action
    updateColor: (state, action) => {
      const { bookId, colorIndex } = action.payload;
      //Find the corresponding book by id
      const book = state.find((b) => b.id === bookId);
      if (book) {
        //then change the book.colorIndex to the corresponding inputted colorIndex
        book.colorIndex = colorIndex;
        //Save to localStorage
        saveToLocalStorage("booksData", state);
      }
    },
  },
});

//Export actions generated by createSlice
export const { updateColor } = booksSlice.actions;
//Export the reducer function
export default booksSlice.reducer;
