// src/store/cartSlice.js

// Imports //

//Import createSlice from redux-toolkit
import { createSlice } from "@reduxjs/toolkit";
//Import the UUID library
//UUID v4 generates a universally unique identifier based on random numbers
import { v4 as uuidv4 } from "uuid";
//Import load and save sessionStorage utilities
import {
  loadFromSessionStorage,
  saveToSessionStorage,
} from "../utils/sessionStorageUtils.js";

//Initial state loaded from sessionStorage
const initialState = loadFromSessionStorage("cart", { items: [] });

// Create slice //

//Create a cartSlice
const cartSlice = createSlice({
  name: "cart",
  initialState,
  //Declare reducers
  reducers: {
    //Add to cart reducer action
    addToCart: (state, action) => {
      const { bookId, title, author, color, image, quantity, price } =
        action.payload;

      //construct a new item
      const newItem = {
        //Assign the unique uuid
        itemId: uuidv4(),
        bookId,
        title,
        author,
        color,
        image,
        quantity,
        unitPrice: price,
        total: price * quantity,
      };
      //Push the item to state.items
      state.items.push(newItem);
      //Save to session storage
      saveToSessionStorage("cart", state);
    },
    //Add a targeted item deletion reducer action (clearItem)
    clearItem: (state, action) => {
      //Filter the cart items to remove the item with a matching itemId item
      state.items = state.items.filter(
        (item) => item.itemId !== action.payload
      );
      //Save to sessionStorage
      saveToSessionStorage("cart", state);
    },
    //Add a reducer to remove all items from the cart
    clearCart: (state) => {
      //Reset the state to empty
      state.items = [];
      //Save to sessionStorage
      saveToSessionStorage("cart", state);
    },
    //Add a reducer to change the quantity of a select book item in the cart
    updateItemQuantity: (state, action) => {
      const { itemId, quantity } = action.payload;
      //Find the item corresponding to the item id
      const item = state.items.find((item) => item.itemId === itemId);
      //if the item is found and the quantity selected is > 1...
      if (item && quantity >= 1) {
        //...then set the item.quantity to the input quantity
        item.quantity = quantity;
        //And set the item.total to the item.unitPrice * input quantity
        item.total = item.unitPrice * quantity;
        //Save to sessionStorage
        saveToSessionStorage("cart", state);
      }
    },
  },
});

//Export actions generated by createSlice
export const { addToCart, clearItem, clearCart, updateItemQuantity } =
  cartSlice.actions;
//Export the reducer function
export default cartSlice.reducer;
