// src/store/loginSlice.js

// Imports //

//Import createSlice from redux-toolkit
import { createSlice } from "@reduxjs/toolkit";
//Import load and save sessionStorage utilities
import {
  loadFromSessionStorage,
  saveToSessionStorage,
} from "../utils/sessionStorageUtils.js";

//Initial state loaded from sessionStorage
const initialState = loadFromSessionStorage("loginState", {
  isLoggedIn: false,
  username: "",
});

// Create slice //

//Create a loginSlice
const loginSlice = createSlice({
  name: "login",
  initialState,
  //Declare reducers
  reducers: {
    //Login reducer action
    login(state, action) {
      //set isLoggedIn to true
      state.isLoggedIn = true;
      //Set username to form input payload
      state.username = action.payload.username;
      //Save to sessionStorage
      saveToSessionStorage("loginState", state);
    },
    logout(state) {
      //Reset state to default state
      state.isLoggedIn = false;
      state.username = "";
      //Clear from sessionStorage
      saveToSessionStorage("loginState", {
        //Reset state to default state
        isLoggedIn: false,
        username: "",
      });
    },
  },
});

//Export actions generated by createSlice
export const { login, logout } = loginSlice.actions;
//Export the reducer function
export default loginSlice.reducer;
