//loginSlice.js

// Imports //

//Import createSlice from redux-toolkit
import { createSlice } from "@reduxjs/toolkit";
//Import load and save localStorage utilities
import {
  loadFromLocalStorage,
  saveToLocalStorage,
} from "../utils/localStorageUtils.js";

//Initial state loaded from localStorage
const initialState = loadFromLocalStorage("loginState", {
  isLoggedIn: false,
  username: "",
  email: "",
});

// Create slice //

//Create a loginSlice
const loginSlice = createSlice({
  name: "login",
  initialState,
  //Declare reducers
  reducers: {
    //Login reducer action
    login(state, action) {
      //set isLoggedIn to true
      state.isLoggedIn = true;
      //Set username to form input payload
      state.username = action.payload.username;
      //Set email to form input payload
      state.email = action.payload.email;
      //Save to localStorage
      saveToLocalStorage("loginState", state);
    },
    logout(state) {
      //Reset state to default state
      state.isLoggedIn = false;
      state.username = "";
      state.email = "";
      //Clear from localStorage
      saveToLocalStorage("loginState", {
        //Reset state to default state
        isLoggedIn: false,
        username: "",
        email: "",
      });
    },
  },
});

//Export actions generated by createSlice
export const { login, logout } = loginSlice.actions;
//Export the reducer function
export default loginSlice.reducer;
