//ordersSlice.js

// Imports //

//Import createSlice from redux-toolkit
import { createSlice } from "@reduxjs/toolkit";
//Import the UUID library
//UUID v4 generates a universally unique identifier based on random numbers
import { v4 as uuidv4 } from "uuid";
//Import load and save localStorage utilities
import {
  loadFromLocalStorage,
  saveToLocalStorage,
} from "../utils/localStorageUtils.js";

//Initial state loaded from localStorage
const initialState = loadFromLocalStorage("orders", []);

// Create slice //

//Create ordersSlice
const ordersSlice = createSlice({
  name: "orders",
  initialState,
  //Declare reducers
  reducers: {
    //A reducer action for placing an order
    placeOrder: (state, action) => {
      const { items, total, shippingMethod, shippingCost, username } =
        action.payload;

      //Construct a new order item
      const newOrder = {
        //Generate a random UUID order number
        orderId: uuidv4(),
        //Save the date as an ISO formatted string to provide to user
        date: new Date().toISOString(),
        //Save the username to ensure the user ONLY views their orders
        username,
        //Save the shipping method to provide stored user order shipping info
        shippingMethod,
        //Save the shipping cost, so that the user gets an accurate breakdown of all costs
        shippingCost,
        //Save external total as it more than the sum of items costs
        total,
        //Provide array of order items
        items: items.map((item) => ({
          //Internal tracking (Would be used in a real store)
          itemId: item.itemId,
          //Internal tracking (Would be used in a real store)
          bookId: item.bookId,
          //For user display per item
          title: item.title,
          author: item.author,
          color: item.color,
          image: item.image,
          unitPrice: item.unitPrice,
          quantity: item.quantity,
          total: item.total,
        })),
      };
      //push the newOrder to the state
      state.push(newOrder);
      //Save to localStorage
      saveToLocalStorage("orders", state);
    },
  },
});

//Export actions generated by createSlice
export const { placeOrder } = ordersSlice.actions;
//Export the reducer function
export default ordersSlice.reducer;
