//userSlice.js

// Imports //

//Import createSlice from redux-toolkit
import { createSlice } from "@reduxjs/toolkit";
//Import load and save sessionStorage utilities
import {
  loadFromSessionStorage,
  saveToSessionStorage,
} from "../utils/sessionStorageUtils.js";

//Initial state loaded from sessionStorage
const initialState = loadFromSessionStorage("users", []);

// Create slice //

//Create a userSlice
const userSlice = createSlice({
  name: "users",
  initialState,
  //Declare reducers
  reducers: {
    //Add user reducer action
    addUser: (state, action) => {
      //Push constructed user as payload to state as array object
      state.push(action.payload);
      //Save to sessionStorage
      saveToSessionStorage("users", state);
    },
  },
});

//Export actions generated by createSlice
export const { addUser } = userSlice.actions;
//Export the reducer function
export default userSlice.reducer;
