// store/signUpAlertSlice.js

// Imports //
import { createSlice } from "@reduxjs/toolkit";
//Import load and save sessionStorage utilities
import {
  loadFromSessionStorage,
  saveToSessionStorage,
} from "../../utils/sessionStorageUtils.js";

//Load initial state from sessionStorage with fallback
const initialState = loadFromSessionStorage("alertState", {
  signUpDisclaimerDismissed: false,
});

// Create slice //

//Create an alertSlice
const signUpAlertSlice = createSlice({
  name: "signUpAlert",
  initialState,
  //Declare reducers
  reducers: {
    //Dismiss signup disclaimer reducer action
    dismissSignUpDisclaimer: (state) => {
      state.signUpDisclaimerDismissed = true;
      //Save to sessionStorage
      saveToSessionStorage("signUpAlertSlice", state);
    },
    //Reset signup disclaimer reducer action
    resetSignUpDisclaimer: (state) => {
      state.signUpDisclaimerDismissed = false;
      //Save to sessionStorage
      saveToSessionStorage("signUpAlertSlice", state);
    },
  },
});

//Export actions generated by createSlice
export const { dismissSignUpDisclaimer, resetSignUpDisclaimer } =
  signUpAlertSlice.actions;
//Export the reducer function
export default signUpAlertSlice.reducer;
